[project]
name = "huggingface-agents-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.49.1",
    "openai>=2.5.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.0.1",
]
